version: 1
root: .
output: dist
target: node

development:
  port: 3000

server:
  main: src/server/server.ts
  controllers: src/server/controller
  middleware: src/middleware
  openapi: src/server/stitch.yaml

client:
  main: src/ui/frontend.ts
  shell: src/ui/index.html
  openapi: src/ui/stitch.yaml
  components: src/ui

assets:
  - src/ui/resources/images/**
  - src/ui/resources/**
  - migrations/**/*.sql
