// Kazibee frontend entry (v1). `noego:frontend` is generated by @noego/app
// at build time from src/ui/openapi/** (x-view / x-layout / fallback):
// the route manifest, a path matcher, and mountFrontend(), which hydrates
// forge's RecursiveRender over the server-rendered markup using
// window.__INITIAL_DATA__ (same components + props the server used).
import { mountFrontend } from 'noego:frontend';

mountFrontend();
