// Ambient types for the build-time virtual module generated by @noego/app.
declare module 'noego:frontend' {
  export interface FrontendRoute {
    path: string | null;
    method: string;
    pattern?: RegExp;
    keys?: string[];
    view: unknown;
    layouts: unknown[];
  }
  export interface FrontendMatch {
    route: FrontendRoute;
    params: Record<string, string>;
    fallback: boolean;
  }
  export const routes: FrontendRoute[];
  export const fallback: FrontendRoute | null;
  export function matchFrontendRoute(pathname: string): FrontendMatch | null;
  export function mountFrontend(options?: { target?: HTMLElement }): unknown;
}
