/**
 * HTML Templates for Forge Visual Testing
 *
 * Placeholders (all required):
 * - {{{HEAD}}} - Content from <svelte:head> (title, meta, links)
 * - {{{CSS}}}  - Component CSS generated by Svelte
 * - {{{APP}}}  - Server-rendered component HTML
 */

/**
 * Tailwind CSS template for rendering HTML screenshots
 */
export const TAILWIND_TEMPLATE = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet">
  <script>
    window.tailwind = window.tailwind || {};
    window.tailwind.config = {
      theme: {
        extend: {
          colors: {
            honey: {
              50: '#fffbeb',
              100: '#fef3c7',
              200: '#fde68a',
              300: '#fcd34d',
              400: '#fbbf24',
              500: '#f59e0b',
              600: '#d97706',
              700: '#b45309',
            },
            ink: {
              DEFAULT: '#0a0a0a',
              light: '#1a1a1a',
              muted: '#525252',
              faint: '#a3a3a3',
            }
          },
          fontFamily: {
            sans: ['Inter', 'system-ui', 'sans-serif'],
            mono: ['JetBrains Mono', 'monospace'],
          }
        }
      }
    };
  </script>
  <script src="https://cdn.tailwindcss.com"></script>
  {{{HEAD}}}
  <style>
    body {
      margin: 0;
      font-family: 'Inter', system-ui, sans-serif;
      background: #ffffff;
      color: #0a0a0a;
      -webkit-font-smoothing: antialiased;
    }
    .honey-glow { box-shadow: 0 0 30px rgba(245, 158, 11, 0.1); }
    .gradient-text {
      background: linear-gradient(135deg, #f59e0b 0%, #d97706 100%);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
    }
  </style>
  <style>{{{CSS}}}</style>
</head>
<body>
  <div id="app">{{{APP}}}</div>
</body>
</html>`;

/**
 * Minimal template without Tailwind
 */
export const BASIC_TEMPLATE = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {{{HEAD}}}
  <style>{{{CSS}}}</style>
</head>
<body>
  <div id="app">{{{APP}}}</div>
</body>
</html>`;

/**
 * Standard viewport sizes for visual testing
 */
export const VIEWPORTS = {
  desktop: { name: 'desktop', width: 1920, height: 1080 },
  tablet: { name: 'tablet', width: 768, height: 1024 },
  mobile: { name: 'mobile', width: 375, height: 812 },
} as const;

export const ALL_VIEWPORTS = Object.values(VIEWPORTS);
