import { execFile } from 'node:child_process';
import { mkdir, readFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { promisify } from 'node:util';

/**
 * HTML Templates for Forge Visual Testing
 *
 * Placeholders (all required):
 * - {{{HEAD}}} - Content from <svelte:head> (title, meta, links)
 * - {{{CSS}}}  - Component CSS generated by Svelte
 * - {{{APP}}}  - Server-rendered component HTML
 */

const execFileAsync = promisify(execFile);
const tailwindOutputPath = resolve('src/ui/resources/css/app.css');

export async function buildTailwindTemplate() {
  await mkdir(dirname(tailwindOutputPath), { recursive: true });
  await execFileAsync('npm', ['run', 'build:css']);

  const tailwindCss = await readFile(tailwindOutputPath, 'utf8');
  return TAILWIND_TEMPLATE.replace('{{{TAILWIND_CSS}}}', tailwindCss);
}

/**
 * Tailwind CSS template for rendering HTML screenshots
 */
export const TAILWIND_TEMPLATE = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet">
  <style>{{{TAILWIND_CSS}}}</style>
  {{{HEAD}}}
  <style>{{{CSS}}}</style>
</head>
<body>
  <div id="app">{{{APP}}}</div>
</body>
</html>`;

/**
 * Minimal template without Tailwind
 */
export const BASIC_TEMPLATE = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {{{HEAD}}}
  <style>{{{CSS}}}</style>
</head>
<body>
  <div id="app">{{{APP}}}</div>
</body>
</html>`;

/**
 * Standard viewport sizes for visual testing
 */
export const VIEWPORTS = {
  desktop: { name: 'desktop', width: 1920, height: 1080 },
  tablet: { name: 'tablet', width: 768, height: 1024 },
  mobile: { name: 'mobile', width: 375, height: 812 },
} as const;

export const ALL_VIEWPORTS = Object.values(VIEWPORTS);
